# -*- coding: utf-8 -*-
"""RSACryptosystemDemonstration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4m6s3R2WIEZJLi5a6RK8TP4mh5VHO4q

# **RSA Cryptosystem Demonstration**
"""

import math

# Function to check prime number
def is_prime(num):
    if num <= 1:
        return False

    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False

    return True


# Function to find GCD
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a


# Extended Euclidean Algorithm
def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1

    gcd_value, x1, y1 = extended_gcd(b % a, a)

    x = y1 - (b // a) * x1
    y = x1

    return gcd_value, x, y


# Function to find modular inverse
def mod_inverse(e, phi):
    gcd_value, x, y = extended_gcd(e, phi)

    if gcd_value != 1:
        return None

    return x % phi


# ---------- INPUT SECTION ----------

try:
    p = int(input("Enter prime number p: "))
    q = int(input("Enter prime number q: "))

except ValueError:
    print("Invalid input! Please enter integer values only.")
    exit()


# ---------- VALIDATION ----------

valid = True

if p <= 0 or q <= 0:
    print("p and q must be positive integers.")
    valid = False

elif not is_prime(p):
    print(f"{p} is not a prime number.")
    valid = False

elif not is_prime(q):
    print(f"{q} is not a prime number.")
    valid = False

elif p == q:
    print("p and q should not be equal.")
    valid = False

elif p < 11 or q < 11:
    print("Choose prime numbers greater than 10.")
    valid = False


# ---------- EXECUTE RSA ONLY IF VALID ----------

if valid:

    n = p * q
    phi = (p - 1) * (q - 1)

    # Select e
    e = 2

    while e < phi:
        if gcd(e, phi) == 1:
            break
        e += 1

    # Generate d
    d = mod_inverse(e, phi)

    if d is None:
        print("Failed to generate modular inverse.")
        exit()

    # Display keys
    print("\nRSA Key Generation Successful")
    print("--------------------------------")
    print("Public Key (e, n): ", (e, n))
    print("Private Key (d, n): ", (d, n))

    # Plaintext input opens ONLY if input is valid
    message = input("\nEnter plaintext message: ")

    if len(message) == 0:
        print("Message cannot be empty.")
        exit()

    # Convert plaintext to ASCII
    ascii_values = [ord(char) for char in message]

    # Check ASCII values
    for value in ascii_values:
        if value >= n:
            print("\nError:")
            print("ASCII value is larger than or equal to n.")
            print("Choose larger prime numbers.")
            exit()

    # Encryption
    ciphertext = [pow(value, e, n) for value in ascii_values]

    print("\nEncrypted Ciphertext:")
    print(ciphertext)

    # Decryption
    decrypted_ascii = [pow(value, d, n) for value in ciphertext]

    decrypted_message = ''.join(chr(value) for value in decrypted_ascii)

    print("\nDecrypted Message:")
    print(decrypted_message)

else:
    print("\nRSA execution terminated due to invalid inputs.")